version: '3.8'
services:
  frontend:
    build: ./client
    ports:
      - "3000:3000"

  backend:
    build: ./server

    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: adminadmin
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db-data:

